/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christy
 */
import java.util.*;

public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    private String result = ("");

    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OutputScreen = new javax.swing.JTextArea();
        Button1 = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        ButtonDivision = new javax.swing.JButton();
        ButtonMultiply = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDecimalPoint = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonAllClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        OutputScreen.setColumns(20);
        OutputScreen.setRows(5);
        OutputScreen.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(OutputScreen);
        OutputScreen.getAccessibleContext().setAccessibleParent(OutputScreen);

        Button1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button1.setText("1");
        Button1.setToolTipText("");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        ButtonMinus.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button4.setText("4");
        Button4.setToolTipText("");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button7.setText("7");
        Button7.setToolTipText("");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button2.setText("2");
        Button2.setToolTipText("");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button8.setText("8");
        Button8.setToolTipText("");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button5.setText("5");
        Button5.setToolTipText("");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button3.setText("3");
        Button3.setToolTipText("");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button9.setText("9");
        Button9.setToolTipText("");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button6.setText("6");
        Button6.setToolTipText("");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        ButtonAdd.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        ButtonAdd.setText("+");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonDivision.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        ButtonDivision.setText("/");
        ButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivisionActionPerformed(evt);
            }
        });

        ButtonMultiply.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        ButtonMultiply.setText("x");
        ButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplyActionPerformed(evt);
            }
        });

        ButtonEqual.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        ButtonEqual.setText("=");
        ButtonEqual.setToolTipText("");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        Button0.setText("0");
        Button0.setToolTipText("");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonDecimalPoint.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        ButtonDecimalPoint.setText(".");
        ButtonDecimalPoint.setToolTipText("");
        ButtonDecimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecimalPointActionPerformed(evt);
            }
        });

        ButtonClear.setFont(new java.awt.Font("MingLiU-ExtB", 1, 20)); // NOI18N
        ButtonClear.setText("C");
        ButtonClear.setPreferredSize(new java.awt.Dimension(59, 39));
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonAllClear.setFont(new java.awt.Font("MingLiU-ExtB", 1, 20)); // NOI18N
        ButtonAllClear.setText("AC");
        ButtonAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAllClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonDecimalPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(ButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(ButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDecimalPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        result += "1";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        result += "4";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        result += "7";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        result += "2";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        result += "8";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        result += "5";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        result += "3";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        result += "9";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        result += "6";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button6ActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        if (check(result)) {
            result = Operation(result);

            //Omit decimal points if result ends with ".0"
            if (result.substring(result.length() - 2, result.length()).equals(".0")) {
                result = result.substring(0, result.length() - 2);
            }

            OutputScreen.setText(result);
        }
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        result += "0";
        OutputScreen.setText(result);
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        result += " - ";
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        result += " + ";
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplyActionPerformed
        result += " x ";
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonMultiplyActionPerformed

    private void ButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivisionActionPerformed
        result += " / ";
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonDivisionActionPerformed

    private void ButtonDecimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecimalPointActionPerformed
        result += ".";
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonDecimalPointActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        result = result.substring(0, result.length() - 1);
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAllClearActionPerformed
        result = ("");
        OutputScreen.setText(result);
    }//GEN-LAST:event_ButtonAllClearActionPerformed

    private static String Operation(String s) {
        String[] ch = s.split(" ");
        Stack<String> st = new Stack<>();
        st.clear();

        int i = 0;
        //x and / Operation
        while (st.search("x") != -1 || st.search("/") != -1 || i < ch.length) {
            switch (ch[i]) {
                case "x": {
                    Double n1 = Double.parseDouble(st.pop());
                    Double n2 = Double.parseDouble(ch[i + 1]);
                    i++;
                    st.push(Double.toString(n1 * n2));
                    break;
                }
                case "/": {
                    Double n1 = Double.parseDouble(st.pop());
                    Double n2 = Double.parseDouble(ch[i + 1]);
                    i++;
                    n1 /= n2;
                    st.push(Double.toString(n1));
                    //System.out.println(n1 + " " + n2 + " "+ n1 / n2);
                    break;
                }
                default:
                    st.push(ch[i]);
                    break;
            }
            i++;
        }

        int stackSize = st.size();
        i = 0;
        while (!st.empty()) {
            ch[stackSize - i - 1] = (String) st.pop();
            i++;
        }

        i = 0;
        //+ and - Operation 
        while (st.search("+") != -1 || st.search("-") != -1 || i < stackSize) {
            switch (ch[i]) {
                case "+": {
                    Double n1 = Double.parseDouble(st.pop());
                    Double n2 = Double.parseDouble(ch[i + 1]);
                    i++;
                    st.push(Double.toString(n1 + n2));
                    break;
                }
                case "-": {
                    Double n1 = Double.parseDouble(st.pop());
                    Double n2 = Double.parseDouble(ch[i + 1]);
                    i++;
                    st.push(Double.toString(n1 - n2));
                    break;
                }
                default:
                    st.push(ch[i]);
                    break;
            }
            i++;
        }
        return (st.pop());
    }

    private static boolean check(String s) {
        int OperatorCount = 0;
        int OperandCount = 0;
        String[] ch = s.split(" ");
        //check for consecutive operators
        for (int i = 0; i < ch.length - 1; i++) {
            if ((ch[i].contains("+") || ch[i].contains("-") || ch[i].contains("x") || ch[i].contains("/"))
                    && (ch[i + 1].contains("+") || ch[i + 1].contains("-") || ch[i + 1].contains("x") || ch[i + 1].contains("/"))) {
                return false;
            }
        }
        //check for consecutive operands	
        for (int i = 0; i < ch.length - 1; i++) {
            if (ch[i].matches("\\d+(\\.\\d+)?") && ch[i + 1].matches("\\d+(\\.\\d+)?")) {
                return false;
            }
        }
        //check if number of operator and operand are correct	
        for (String t : ch) {
            if (t.matches("\\d+(\\.\\d+)?")) {
                OperandCount++;
            } else if (t.contains("+") || t.contains("-")
                    || t.contains("x") || t.contains("/")) {
                OperatorCount++;
            }
        }
        return (OperandCount - 1 == OperatorCount);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonAllClear;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDecimalPoint;
    private javax.swing.JButton ButtonDivision;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMultiply;
    private javax.swing.JTextArea OutputScreen;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
